name: neofit_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  go_router: ^10.0.0
  hooks_riverpod: ^2.3.8
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
