name: neofit_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  analyzer: ^6.2.0
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  dynamic_color: ^1.6.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.8
  formz: ^0.6.1
  go_router: ^10.0.0
  hive: ^2.2.3
  hooks_riverpod: ^2.3.8
  intl: any
  intl_utils: ^2.8.5
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
  #   - assets/images/
